<?xml version="1.0" encoding="utf-8"?><Database Name="OrdersManagement" Class="OrdersDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-K49NMUH\SQLEXPRESS;Initial Catalog=OrdersManagement;Integrated Security=True" SettingsObjectName="OrdersManagement1.Properties.Settings" SettingsPropertyName="OrdersManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CUSTOMER" Member="CUSTOMERs">
    <Type Name="CUSTOMER">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Money" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="CUSTOMER_ORDER" Member="ORDERs" ThisKey="Id" OtherKey="CUSTOMER_Id" Type="ORDER" />
    </Type>
  </Table>
  <Table Name="dbo.[ORDER]" Member="ORDERs">
    <Type Name="ORDER">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CUSTOMER_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ORDER_ORDER_DETAIL" Member="ORDER_DETAILs" ThisKey="Id" OtherKey="ORDER_Id" Type="ORDER_DETAIL" />
      <Association Name="CUSTOMER_ORDER" Member="CUSTOMER" ThisKey="CUSTOMER_Id" OtherKey="Id" Type="CUSTOMER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ORDER_DETAIL" Member="ORDER_DETAILs">
    <Type Name="ORDER_DETAIL">
      <Column Name="Quantity" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PRODUCT_Article" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ORDER_Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ORDER_ORDER_DETAIL" Member="ORDER" ThisKey="ORDER_Id" OtherKey="Id" Type="ORDER" IsForeignKey="true" />
      <Association Name="PRODUCT_ORDER_DETAIL" Member="PRODUCT" ThisKey="PRODUCT_Article" OtherKey="Article" Type="PRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT" Member="PRODUCTs">
    <Type Name="PRODUCT">
      <Column Name="Article" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Cost" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="PRODUCT_ORDER_DETAIL" Member="ORDER_DETAILs" ThisKey="Article" OtherKey="PRODUCT_Article" Type="ORDER_DETAIL" />
    </Type>
  </Table>
</Database>